<?php
/**
 *
 * @author Ananaskelly
 */
use Illuminate\Support\Collection;
use App\BoardInfo;

class BoardInfoWithGameRelationTest extends TestCase
{
    /**
     *
     * @var BoardInfo
     */
    protected $boardInfo;
    
    public function setUp()
    {
        parent::setUp();
        $this->boardInfo = factory(BoardInfo::class)->create();
    }
    
    public function testBoardInfoToGameRelation()
    {
        $boardInfo = $this->boardInfo;
        $this->assertEquals($boardInfo->game->id, $boardInfo->game_id);
    }

    public function testGameToBoardInfosIsCollection()
    {
        $boardInfo = $this->boardInfo;
        $game = $boardInfo->game;
        $this->assertTrue($game->boardInfos instanceof Collection);
    }
    
    /**
     *
     * @depends testGameToBoardInfosIsCollection
     */
    public function testGameToBoardInfosRelation()
    {
        $boardInfo = $this->boardInfo;
        $game = $boardInfo->game;
        $this->assertTrue($game->boardInfos->contains($boardInfo));
    }
    
    public function tearDown()
    {
        $boardInfo = $this->boardInfo;
        $game = $boardInfo->game;
        $boardInfo->delete();
        /*
         * Delete related autogenerated models also
         */
        $game->delete();
        $game->gameType->delete();
        parent::tearDown();
    }
}
