<?php
/**
 *
 * @author malinink
 */
use Illuminate\Support\Collection;
use App\Game;

class GameWithGameTypeRelationTest extends TestCase
{
    /**
     *
     * @var Game
     */
    protected $game;
    
    public function setUp()
    {
        parent::setUp();
        $this->game = factory(Game::class)->create();
    }
    
    public function testGameToGameTypeRelation()
    {
        $game = $this->game;
        $this->assertEquals($game->gameType->id, $game->game_type_id);
    }

    public function testGameTypeToGamesIsCollection()
    {
        $game = $this->game;
        $gameType = $game->gameType;
        $this->assertTrue($gameType->games instanceof Collection);
    }
    
    /**
     *
     * @depends testGameTypeToGamesIsCollection
     */
    public function testGameTypeToGamesRelation()
    {
        $game = $this->game;
        $gameType = $game->gameType;
        $this->assertTrue($gameType->games->contains($game));
    }
    
    public function tearDown()
    {
        $game = $this->game;
        $game->delete();
        /*
         * Delete related autogenerated models also
         */
        $game->gameType->delete();
        parent::tearDown();
    }
}
