<?php
/**
 *
 * @author malinink
 */
use App\User;
use App\GameType;
use App\Game;

use App\UserIngameInfo;

class ModelsFactoriesTest extends TestCase
{
    /**
     * Test User Factory
     *
     * @return void
     */
    public function testUserFactory()
    {
        $user = factory(User::class)->create();
        $user->delete();
    }

    /**
     * Test GameType Factory
     *
     * @return void
     */
    public function testGameTypeFactory()
    {
        $gameType = factory(GameType::class)->create();
        $gameType->delete();
    }
    
    /**
     * Test Game Factory
     *
     * @return void
     */
    public function testGameFactory()
    {
        $game = factory(Game::class)->create();
        $game->delete();
        /*
         * Delete related autogenerated models also
         */
        $game->gameType->delete();
    }
    
    /**
     * Test UserIngameInfo Factory
     *
     * @return void
     */
    public function testUserIngameInfoFactory()
    {
        $user_ingame = factory(UserIngameInfo::class)->make();
        $user_ingame->save();
        $user_ingame->delete();
        /*
         * Delete related autogenerated models also
         */
        $user_ingame->gameType->delete();
        $user_ingame->user->delete();
    }
}
