<?php
/**
 *
 * @author Ananaskelly
 */
use Illuminate\Support\Collection;
use App\TurnInfo;

class TurnInfoWithGameRelationTest extends TestCase
{
    /**
     *
     * @var TurnInfo
     */
    protected $turnInfo;
    
    public function setUp()
    {
        parent::setUp();
        $this->turnInfo = factory(TurnInfo::class)->create();
    }
    
    public function testTurnInfoToGameRelation()
    {
        $turnInfo = $this->turnInfo;
        $this->assertEquals($turnInfo->game->id, $turnInfo->game_id);
    }

    public function testGameToTurnInfosIsCollection()
    {
        $turnInfo = $this->turnInfo;
        $game = $turnInfo->game;
        $this->assertTrue($game->turnInfos instanceof Collection);
    }
    
    /**
     *
     * @depends testGameToTurnInfosIsCollection
     */
    public function testGameToTurnInfosRelation()
    {
        $turnInfo = $this->turnInfo;
        $game = $turnInfo->game;
        $this->assertTrue($game->turnInfos->contains($turnInfo));
    }
    
    public function tearDown()
    {
        $turnInfo = $this->turnInfo;
        $game = $turnInfo->game;
        $turnInfo->delete();
        /*
         * Delete related autogenerated models also
         */
        $game->delete();
        $game->gameType->delete();
        parent::tearDown();
    }
}
