<?php
/**
 *
 * @author Ananaskelly
 */
use Illuminate\Support\Collection;
use App\UserGame;

class UserGameWithGameRelationTest extends TestCase
{
    /**
     *
     * @var UserGame
     */
    protected $userGame;
    
    public function setUp()
    {
        parent::setUp();
        $this->userGame = factory(UserGame::class)->create();
    }
    
    public function testUserGameToGameRelation()
    {
        $userGame = $this->userGame;
        $this->assertEquals($userGame->game->id, $userGame->game_id);
    }

    public function testGameToUserGamesIsCollection()
    {
        $userGame = $this->userGame;
        $game = $userGame->game;
        $this->assertTrue($game->userGames instanceof Collection);
    }
    
    /**
     *
     * @depends testGameToUserGamesIsCollection
     */
    public function testGameToUserGamesRelation()
    {
        $userGame = $this->userGame;
        $game = $userGame->game;
        $this->assertTrue($game->userGames->contains($userGame));
    }
    
    public function tearDown()
    {
        $userGame = $this->userGame;
        $game = $userGame->game;
        $userGame->delete();
        /*
         * Delete related autogenerated models also
         */
        $game->delete();
        $userGame->user->delete();
        $userGame->user->gameType->delete();
        $game->gameType->delete();
        parent::tearDown();
    }
}
