<?php
/**
 *
 * @author learp
 */

use Illuminate\Support\Collection;
use App\Token;

class UserWithTokenRelationTest extends TestCase
{
    /**
     *
     * @var $Token
     */
    protected $Token;
    
    public function setUp()
    {
        parent::setUp();
        $this->Token = factory(Token::class)->create();
    }
    
    public function testUserToTokenIsCollection()
    {
        $Token = $this->Token;
        $user = $Token->user;
        $this->assertTrue($user->Token instanceof Collection);
    }
    
    /**
     *
     * @depends testUserToTokenIsCollection
     */
    public function testUserToTokenRelation()
    {
        $Token = $this->Token;
        $user = $Token->user;
        $this->assertTrue($user->Token->contains($Token));
    }
    
    public function testTokenToUserRelation()
    {
        $this->assertEquals($this->Token->user->id, $this->Token->user_id);
    }
    
    public function tearDown()
    {
        $Token = $this->Token;
        /*
         * Delete related autogenerated models also
         */
        $Token->user->gameType->delete();
        $Token->user->delete();
        $Token->delete();
        parent::tearDown();
    }
}
